(async()=>{
 const slug=new URLSearchParams(location.search).get('course');const message=document.getElementById('classroom-message');const button=document.getElementById('course-checkout');
 const allowed=new Set(['cloud-fundamentals-101','az-900-azure-fundamentals','az-104-azure-administrator','az-305-azure-solutions-architect','ai-901-azure-ai-fundamentals','ai-fundamentals-everyday-ai','cloud-security','ai-security-responsible-governance','cyber-basics-stay-safer-online']);
 if(!allowed.has(slug)){message.textContent='Choose a course from the course hub to check enrollment.';return;}
 const token=localStorage.getItem('dct_token');if(!token){message.textContent='Sign in to check your enrolled course. Gumroad starter purchases are accessed through your Gumroad library.';return;}
 const api='https://energetic-endurance-production.up.railway.app/api';
 try{const r=await fetch(`${api}/hub/courses/${encodeURIComponent(slug)}/content`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});if(!r.ok){if(r.status===401||r.status===403)message.textContent='Your signed-in account needs verified paid enrollment for this classroom. If you bought the Cloud 101 starter on Gumroad, use your Gumroad library.';else message.textContent='Your classroom is being prepared or enrollment could not be verified. Please contact DCT for access help.';}
 else{const data=await r.json();const frame=document.createElement('iframe');frame.title='Your enrolled course';frame.className='classroom-frame';frame.setAttribute('sandbox','allow-scripts');
 // Isolate course scripts; do not give imported HTML access to the parent login token.
 frame.srcdoc=data.html.replace('<head>','<head><base href="https://thedopecloudteacher.org/hub/courses/">').replace(/<script src="\/js\/[^>]*><\/script>/g,'');document.getElementById('classroom-content').append(frame);message.textContent='Enrollment verified. Your course is open below.';return;}
 const cr=await fetch(`${api}/hub/catalog`,{cache:'no-store'});if(cr.ok){const catalog=await cr.json();const course=catalog.courses.find(c=>c.id===slug&&c.checkoutReady);if(course){button.hidden=false;button.textContent=`Enroll securely · $${course.price}`;button.onclick=async()=>{button.disabled=true;try{const checkout=await fetch(`${api}/create-checkout`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({courseId:slug})});const data=await checkout.json();if(!checkout.ok)throw new Error();const url=new URL(data.url);if(url.origin!=='https://checkout.stripe.com')throw new Error();location.assign(url.href);}catch(_){message.textContent='Checkout is unavailable. Please contact DCT before purchasing.';button.disabled=false;}};}}}
 catch(_){message.textContent='We could not reach your classroom right now. Please contact DCT for enrollment help.';}
})();
