(() => {
  const key='dct:instructor-preparation:v1';const boxes=[...document.querySelectorAll('[data-module]')];
  let saved=[];try{saved=JSON.parse(localStorage.getItem(key))||[];}catch(_){}
  const status=document.getElementById('prep-message');const submit=document.getElementById('submit-prep');
  function selected(){return boxes.filter(b=>b.checked).map(b=>b.dataset.module);}
  function update(){const ids=selected();document.getElementById('prep-count').textContent=`${ids.length} of 6 preparation blocks ready`;submit.disabled=ids.length!==6;try{localStorage.setItem(key,JSON.stringify(ids));}catch(_){} }
  boxes.forEach(b=>{b.checked=Array.isArray(saved)&&saved.includes(b.dataset.module);b.addEventListener('change',update);});update();
  const docs={pending:'<p>Confirm your agreement and start date with DCT before completing personnel paperwork. DCT will provide the applicable agreement, policies and private document process.</p>',employee:'<ol><li>Review and sign the employment agreement and required policies using the approved staff process.</li><li><a href="https://www.irs.gov/forms-pubs/about-form-w-4" target="_blank" rel="noopener">Get the official W-4 and instructions</a> for federal withholding; DCT provides applicable state withholding steps.</li><li><a href="https://www.uscis.gov/i-9" target="_blank" rel="noopener">Get the official I-9 and instructions</a>. Complete verification with DCT’s authorized representative using the official instructions and timing.</li><li>Complete payroll setup in the private personnel service DCT designates.</li><li>Confirm any role-specific screening, safeguarding and host-site requirements with DCT.</li></ol>',contractor:'<ol><li>Review and sign the services agreement, scope, rate, invoicing terms and relevant policies.</li><li><a href="https://www.irs.gov/forms-pubs/about-form-w-9" target="_blank" rel="noopener">Get the official W-9 and instructions</a> if applicable to your tax status. DCT confirms any different tax documentation needed.</li><li>Provide required business or insurance documentation through the private staff process, if requested.</li><li>Confirm safeguarding, host-site requirements and your teaching assignment.</li></ol><p>Independent contractors do not complete I-9 as DCT employees. DCT must confirm the correct work arrangement; this selection does not make that determination. <a href="https://www.uscis.gov/i-9-central/complete-correct-form-i-9/exceptions" target="_blank" rel="noopener">Official I-9 exceptions</a>.</p>'};
  const track=document.getElementById('work-track');function showDocs(){document.getElementById('document-track').innerHTML=docs[track.value];}track.addEventListener('change',showDocs);showDocs();
  document.getElementById('download-prep').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({preparation:selected(),status:'Self-reported preparation; DCT review required'},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='DCT-instructor-preparation.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);});
  submit.addEventListener('click',async()=>{
    const token=localStorage.getItem('dct_token');if(!token){status.textContent='Sign in to request a preparation review. Your checklist stays saved on this browser.';return;}
    submit.disabled=true;status.textContent='Sending your preparation checklist…';
    try{const r=await fetch('https://energetic-endurance-production.up.railway.app/api/instructors/readiness',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify({modules:selected()})});if(!r.ok)throw new Error();status.textContent='Your preparation checklist was submitted. DCT review is pending; please arrange your practice lesson with DCT.';}
    catch(_){status.textContent='We could not submit your checklist right now. Contact DCT to arrange the practice review; your browser checklist is saved.';}finally{update();}
  });
})();
